backend/controllers/DataExchangeController.php
<?php

namespace backend\controllers;

use Yii;
use yii\data\ActiveDataProvider;
use yii\data\Pagination;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use bitco\exchange\entities\DataExchange;

/**
 * DataExchangeController implements the CRUD actions for DataExchange model.
 */
class DataExchangeController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all DataExchange models.
     * @return mixed
     */
    public function actionIndex()
    {
        $query = DataExchange::find()->orderBy(['id' => SORT_DESC]);
        $countQuery = clone $query;
        $pages = new Pagination(['totalCount' => $countQuery->count(), 'pageSize' => 5]);
        $dataProvider = new ActiveDataProvider([
            'query' => $query,
            'pagination' => $pages,
        ]);
        $models = $query->offset($pages->offset)->limit($pages->limit)->all();

        return $this->render('index', [
            'models' => $models,
            'dataProvider' => $dataProvider,
            'pages' => $pages,
        ]);
    }

    /**
     * Displays a single DataExchange model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new DataExchange model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new DataExchange();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing DataExchange model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing DataExchange model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the DataExchange model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return DataExchange the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = DataExchange::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/views/data-exchange/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use bitco\exchange\helpers\DataExchangeStatusHelper;

/* @var $this yii\web\View */
/* @var $model bitco\exchange\entities\DataExchange */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="data-exchange-form">

    <?php $form = ActiveForm::begin(); ?>

        <?php //echo $form->field($model, 'exchange_direction')->textInput() ?>

        <?php //echo $form->field($model, 'incoming_amount')->textInput(['maxlength' => true]) ?>

        <?php //echo $form->field($model, 'outgoing_amount')->textInput(['maxlength' => true]) ?>

        <?php //echo $form->field($model, 'level_exchange')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'real_outgoing_amount')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'real_level_exchange')->textInput(['maxlength' => true]) ?>

        <?php //echo $form->field($model, 'user_id')->textInput() ?>

        <?php //echo  $form->field($model, 'user_fullname')->textInput(['maxlength' => true]) ?>

        <?//= $form->field($model, 'user_name')->textInput(['maxlength' => true]) ?>

        <?//= $form->field($model, 'user_email')->textInput(['maxlength' => true]) ?>

        <?//= $form->field($model, 'user_phone')->textInput(['maxlength' => true]) ?>

        <?//= $form->field($model, 'user_purse')->textInput(['maxlength' => true]) ?>

        <?= $form->field($model, 'status')->dropDownList(DataExchangeStatusHelper::statusList()) ?>

        <?//= $form->field($model, 'created_at')->textInput() ?>

        <?//= $form->field($model, 'updated_at')->textInput() ?>

        <?php //echo $form->field($model, 'admin_user_id')->textInput() ?>

    <div class="form-group">
        <?= Html::submitButton($model->isNewRecord ? 'Create' : 'Update', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/data-exchange/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model bitco\exchange\entities\DataExchangeSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="data-exchange-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'exchange_direction') ?>

    <?= $form->field($model, 'incoming_amount') ?>

    <?= $form->field($model, 'outgoing_amount') ?>

    <?= $form->field($model, 'level_exchange') ?>

    <?php // echo $form->field($model, 'real_outgoing_amount') ?>

    <?php // echo $form->field($model, 'real_level_exchange') ?>

    <?php // echo $form->field($model, 'user_id') ?>

    <?php // echo $form->field($model, 'user_fullname') ?>

    <?php // echo $form->field($model, 'user_name') ?>

    <?php // echo $form->field($model, 'user_email') ?>

    <?php // echo $form->field($model, 'user_phone') ?>

    <?php // echo $form->field($model, 'user_purse') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'updated_at') ?>

    <?php // echo $form->field($model, 'admin_user_id') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/data-exchange/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $model bitco\exchange\entities\DataExchange */

$this->title = 'Create Data Exchange';
$this->params['breadcrumbs'][] = ['label' => 'Data Exchanges', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="data-exchange-create">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/data-exchange/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use bitco\exchange\helpers\DataExchangeStatusHelper;
use bitco\siteOptions\helpers\directionListHelper;
use yii\widgets\LinkPager;


/* @var $this yii\web\View */
/* @var $models bitco\exchange\forms\ExchangeCreateForm */


$this->title = 'Список заказов';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="data-exchange-index">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?php // echo Html::a('Create Data Exchange', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?php foreach ($models as $value) { ?>
        <div class="panel-group">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a data-toggle="collapse" data-parent="#accordion" href="#collpse<?php echo $value->id; ?>">
                        <div class="row">
                            <div class="col-md-1">Заказ № <?= $value->id ?></div>
                            <div class="col-md-2"><?= $value->user_id ? $value->user_name : 'Гость' ?></div>
                            <div class="col-md-5">обмен: <?=
                                $value->incoming_amount . ' ' . $value->exchangeDirection->inSigns->short_name_currency . ' = '
                                . $value->outgoing_amount . ' ' . $value->exchangeDirection->outSigns->short_name_currency
                                . ' по курсу ' . $value->level_exchange
                                ?>
                            </div>
                            <div class="col-md-1"><?php echo DataExchangeStatusHelper::statusLabel($value->status);  ?></div>
                            <div class="col-md-2">Изменено: <?= \Yii::$app->formatter->asDatetime($value->updated_at); ?></div>
                            <div class="col-md-1"><?= Html::a('', ['data-exchange/update', 'id' => $value->id], ['class' => 'glyphicon glyphicon-pencil']) ?></div>
                        </div>
                    </a>
                </div>


                <div id="collpse<?php echo $value->id; ?>" class="panel-collapse collapse out">
                    <div class="panel-body"><h4>Контактные данные:</h4>
                        <p><?= $value->user_fullname ?></p>
                        <p><?= $value->user_name ?></p>
                        <p>Телефон: <?= $value->user_phone ?></p>
                        <p>Email: <?= $value->user_email ?></p>
                        <p>Эл. кошелек: <?= $value->user_purse ?></p>
                    </div>
                </div>
            </div>
        </div>
    <?php } ?>

        <?php

        echo LinkPager::widget(['pagination' => $pages])
        ?>

</div>

backend/views/data-exchange/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model bitco\exchange\entities\DataExchange */

$this->title = 'Обновление заказа №: ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Список заказов', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => 'Заказ №' . $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'Изменение';
?>
<div class="data-exchange-update">

    <h1><?= Html::encode($this->title) ?></h1>

    <?= $this->render('_form', [
        'model' => $model,
    ]) ?>

</div>

backend/views/data-exchange/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;
use bitco\exchange\helpers\DataExchangeStatusHelper;
use bitco\siteOptions\helpers\directionListHelper;

/* @var $this yii\web\View */
/* @var $model bitco\exchange\entities\DataExchange */

$this->title = 'Заказ №' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Список заказов', 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="data-exchange-view">

    <h1><?= Html::encode($this->title) ?></h1>

    <p>
        <?= Html::a('На список', ['index'], ['class' => 'btn btn-default']) ?>
        <?= Html::a('Update', ['update', 'id' => $model->id], ['class' => 'btn btn-primary']) ?>
        <?= Html::a('Delete', ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'data' => [
                'confirm' => 'Are you sure you want to delete this item?',
                'method' => 'post',
            ],
        ]) ?>
    </p>

    <?= DetailView::widget([
        'model' => $model,
        'attributes' => [
            //'id',
            [
                'attribute' => 'exchange_direction',
                'value' => function ($model) {
                    return directionListHelper::DirectionLabel($model->exchange_direction);
                }
            ],
            'incoming_amount',
            'outgoing_amount',
            'level_exchange',
            'real_outgoing_amount',
            'real_level_exchange',
            'user_id',
            'user_fullname',
            'user_name',
            'user_email:email',
            'user_phone',
            'user_purse',
            [
                'attribute' => 'status',
                'filter' => DataExchangeStatusHelper::statusList(),
                'value' => function ($model) {
                    return DataExchangeStatusHelper::statusLabel($model->status);
                },
                'format' => 'raw',
            ],
            [
                'attribute' =>  'created_at',
                'format' => 'datetime',
            ],
            [
                'attribute' => 'updated_at',
                'format' => 'datetime',
            ],
            //'admin_user_id',
        ],
    ]) ?>

</div>